
package ru.renue.fns.wsdl.client.dto.kkt.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AuthenticationFault", targetNamespace = "urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiAsyncMessageConsumerService/types/1.0")
public class AuthenticationException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AuthenticationFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AuthenticationException(String message, AuthenticationFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AuthenticationException(String message, AuthenticationFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.renue.AuthenticationFault
     */
    public AuthenticationFault getFaultInfo() {
        return faultInfo;
    }

}
