
package ru.renue.fns.wsdl.client.dto.kkt.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MessageNotFoundFault", targetNamespace = "urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiAsyncMessageConsumerService/types/1.0")
public class MessageNotFoundException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MessageNotFoundFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MessageNotFoundException(String message, MessageNotFoundFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MessageNotFoundException(String message, MessageNotFoundFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.renue.MessageNotFoundFault
     */
    public MessageNotFoundFault getFaultInfo() {
        return faultInfo;
    }

}
