
package ru.renue.fns.wsdl.client.dto.kkt.api;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OpenApiAsyncMessageConsumerService", targetNamespace = "urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiAsyncMessageConsumerService/1.0", wsdlLocation = "file:/C:/projects/sales-api/src/main/java/ru/renue/fns/wsdl/client/kkt.wsdl")
public class OpenApiAsyncMessageConsumerService
    extends Service
{

    private final static URL OPENAPIASYNCMESSAGECONSUMERSERVICE_WSDL_LOCATION;
    private final static WebServiceException OPENAPIASYNCMESSAGECONSUMERSERVICE_EXCEPTION;
    private final static QName OPENAPIASYNCMESSAGECONSUMERSERVICE_QNAME = new QName("urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiAsyncMessageConsumerService/1.0", "OpenApiAsyncMessageConsumerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/projects/sales-api/src/main/java/ru/renue/fns/wsdl/client/kkt.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPENAPIASYNCMESSAGECONSUMERSERVICE_WSDL_LOCATION = url;
        OPENAPIASYNCMESSAGECONSUMERSERVICE_EXCEPTION = e;
    }

    public OpenApiAsyncMessageConsumerService() {
        super(__getWsdlLocation(), OPENAPIASYNCMESSAGECONSUMERSERVICE_QNAME);
    }

    public OpenApiAsyncMessageConsumerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPENAPIASYNCMESSAGECONSUMERSERVICE_QNAME, features);
    }

    public OpenApiAsyncMessageConsumerService(URL wsdlLocation) {
        super(wsdlLocation, OPENAPIASYNCMESSAGECONSUMERSERVICE_QNAME);
    }

    public OpenApiAsyncMessageConsumerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPENAPIASYNCMESSAGECONSUMERSERVICE_QNAME, features);
    }

    public OpenApiAsyncMessageConsumerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpenApiAsyncMessageConsumerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OpenApiAsyncMessageConsumerServicePortType
     */
    @WebEndpoint(name = "OpenApiAsyncMessageConsumerServiceEndpoint")
    public OpenApiAsyncMessageConsumerServicePortType getOpenApiAsyncMessageConsumerServiceEndpoint() {
        return super.getPort(new QName("urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiAsyncMessageConsumerService/1.0", "OpenApiAsyncMessageConsumerServiceEndpoint"), OpenApiAsyncMessageConsumerServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpenApiAsyncMessageConsumerServicePortType
     */
    @WebEndpoint(name = "OpenApiAsyncMessageConsumerServiceEndpoint")
    public OpenApiAsyncMessageConsumerServicePortType getOpenApiAsyncMessageConsumerServiceEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiAsyncMessageConsumerService/1.0", "OpenApiAsyncMessageConsumerServiceEndpoint"), OpenApiAsyncMessageConsumerServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPENAPIASYNCMESSAGECONSUMERSERVICE_EXCEPTION!= null) {
            throw OPENAPIASYNCMESSAGECONSUMERSERVICE_EXCEPTION;
        }
        return OPENAPIASYNCMESSAGECONSUMERSERVICE_WSDL_LOCATION;
    }

}
