
package ru.renue.fns.wsdl.client.dto.kkt.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OpenApiAsyncMessageConsumerServicePortType", targetNamespace = "urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiAsyncMessageConsumerService/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OpenApiAsyncMessageConsumerServicePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns ru.renue.GetMessageResponse
     * @throws AuthenticationException
     * @throws MessageNotFoundException
     */
    @WebMethod(operationName = "GetMessage", action = "urn:GetMessageRequest")
    @WebResult(name = "GetMessageResponse", targetNamespace = "urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiAsyncMessageConsumerService/types/1.0", partName = "parameters")
    public GetMessageResponse getMessage(
            @WebParam(name = "GetMessageRequest", targetNamespace = "urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiAsyncMessageConsumerService/types/1.0", partName = "parameters")
                    GetMessageRequest parameters)
        throws AuthenticationException, MessageNotFoundException
    ;

    /**
     *
     * @param parameters
     * @return
     *     returns ru.renue.SendMessageResponse
     * @throws AuthenticationException
     */
    @WebMethod(operationName = "SendMessage", action = "urn:SendMessageRequest")
    @WebResult(name = "SendMessageResponse", targetNamespace = "urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiAsyncMessageConsumerService/types/1.0", partName = "parameters")
    public SendMessageResponse sendMessage(
            @WebParam(name = "SendMessageRequest", targetNamespace = "urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiAsyncMessageConsumerService/types/1.0", partName = "parameters")
                    SendMessageRequest parameters)
        throws AuthenticationException
    ;

}
