
package ru.renue.fns.wsdl.client.dto.auth.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OpenApiMessageConsumerServicePortType", targetNamespace = "urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiMessageConsumerService/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OpenApiMessageConsumerServicePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns ru.renue.GetMessageResponse
     * @throws AuthenticationException
     */
    @WebMethod(operationName = "GetMessage", action = "urn:GetMessageRequest")
    @WebResult(name = "GetMessageResponse", targetNamespace = "urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiMessageConsumerService/types/1.0", partName = "parameters")
    public GetMessageResponse getMessage(
            @WebParam(name = "GetMessageRequest", targetNamespace = "urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiMessageConsumerService/types/1.0", partName = "parameters")
                    GetMessageRequest parameters)
        throws AuthenticationException
    ;

}
